import './nest/import';
// import {dirname, resolve} from 'path';
// import 'babel-polyfill';
// import url from 'url';
// import lodash from 'lodash';
// console.log(lodash.times);
console.log('hello world');
console.log('this is the one for Vue: '+process.env.NODE_ENV);
console.log('for commonJS is it this: '+NODE_ENV);
console.log('and I also added this: '+ENV);
